version: "3"

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    volumes:
      - ".:/cidade_projeto"
      - "./test_scripts:/app/test_scripts"
    ports:
      - "3000:3000"
    depends_on:
      - db

    environment:
      DATABASE_URL: postgres://postgres:root@db/cidade_projeto-dev

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cidade_projeto-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--username=postgres --encoding=UTF-8 --no-instructions --data-checksums --auth=trust --auth-local=trust --auth-host=trust"

volumes:
  postgres_data:
