default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: root
  pool: 5

development:
  <<: *default
  database: cidade_projeto-dev

test:
  <<: *default
  database: cidade_projeto-test
